In [4]:
import numpy as np

# Sistemas de Eq.s Lineares

Dado o sistema $A \vec{x} = \vec{b}$, ou $\begin{bmatrix} a_{11} & a_{12}\\a_{21} & a_{22} \end{bmatrix}\begin{bmatrix} x_1\\x_2\end{bmatrix} = \begin{bmatrix} b_1\\b_2\end{bmatrix}$


queremos encontrar o vetor $\vec{x}$.

In [5]:
# critérios para verificar a convergência do sistema

# critério das linhas/diagonal dominante (falhando, ainda pode convergir)
def linha(A):
    for i in range (len(A)):
        a=0
        for j in range (len(A[0])):
            if i != j:
                a = a + np.abs(A[i][j])
        if np.abs(A[i][i]) <= a:
            return False #diverge
    return True #converge

# critério de sassenfeld
def sassy(A):
    b = np.zeros(len(A))
    for i in range (len(A)):
        for j in range (len(A)):
            if j <= i - 1:
                b[i] = b[i] + b[j]*np.abs(A[i][j])/np.abs(A[i][i])
            if j >= i + 1:
                b[i] = b[i] + np.abs(A[i][j])/np.abs(A[i][i])
        if b[i] >= 1:
            return False #diverge
    return True #converge

# Função que troca as linhas i e p da matriz A
def troca(A,i,p):
    B = np.zeros((len(A),len(A[0])))
    for j in range (len(A)):
        B[j] = A[j]
        if j == i:
            B[i] = A[p]
        if j == p:
            B[p] = A[i]      
    return B

In [8]:
# Método da Eliminação de Gauss
def Egauss(A):
    print('Sendo a matriz aumentada:\n',A)
    # n é número de linhas em A
    n = len(A)
    B = A
    for i in range (0,n-1,1):
        a = 0
        # Procuramos nessa coluna o maior coef. para usar como pivô
        for p in range (i,n,1):
            if np.abs(B[p][i]) > a:
                # ao achar um pivô, guardamos seu valor e a sua linha
                a = B[p][i]
                P = p
        # se não há nenhum pivô, não há solução.
        if a == 0:
            return print('Não há pivô!')

        # trocamos a ordem das linhas.
        if P != i:
            B = troca(B,P,i)
            print('\nTrocamos as linhas:',i+1,'e',P+1,'\n',B)

        # aqui fazemos a eliminação
        for j in range (i+1,n,1):
            if B[j][i] != 0:
                m = B[j][i]/B[i][i]
                for k in range (n+1):
                    B[j][k] = B[j][k]-m*B[i][k]
                print('\nEliminamos o elemento',j+1,i+1,':\n',B)

    # checa se há solução
    if B[n-1][n-1] == 0:
        return print('Não há solução única!')

    # construimos o vetor solução
    x = np.zeros(n)
    x[n-1] = B[n-1][n]/B[n-1][n-1]
    for i in range (n-1,-1,-1):
        x[i] = B[i][n]/B[i][i]
        for j in range (i+1,n,1):
            x[i] = x[i] - B[i][j]*x[j]/B[i][i]
    return print('\nA solução é x =',x)


# Método Iterativo de Jacobi
def Jacobi(A,b,x0,e,N):
    k = 0
    n = len(b)
    print(k,'ª iteração:\nx=',x0)
    while k < N:
        # vetor solução
        x = np.zeros(n)
        y = np.zeros(n)
        # começamos a próxima iteração
        k = k + 1
        for i in range (n):
            x[i] = b[i]/A[i][i]
            for j in range (n):
                if j != i:
                    x[i] = x[i] - A[i][j]*x0[j]/A[i][i]
                # definimos o vetor 'erro'
                y[j] = np.abs(x[j]-x0[j])

        # checa se alcançamos a precisão desejada
        if np.max(y) < e:
            return print('\n',k,'ª iteração:\nx=',x,'\nerro=',np.max(y))

        print('\n',k,'ª iteração:\nx=',x,'\nerro=',np.max(y))
        # atualizamos o valor do chute começamos de novo
        x0 = x
    return

# Método Gauss-Seidel
def GSeidel(A,b,x0,e,N):
    k = 0
    n = len(b)
    print(k,'ª iteração:\nx=',x0)
    while k < N:
        #vetor solução
        x = np.zeros(n)
        y = np.zeros(n)
        #começamos a próxima iteração
        k = k + 1
        for i in range (n):
            x[i] = b[i]/A[i][i]
            for j in range (n):
                #aqui usamos os valores de x calculados nessa iteração
                if j <= i - 1:
                    x[i] = x[i] - A[i][j]*x[j]/A[i][i]
                #aqui usamos os valores de x calculados na última iteração
                if j >= i + 1:
                    x[i] = x[i] - A[i][j]*x0[j]/A[i][i]
                #definimos o vetor 'erro'
                y[j] = np.abs(x[j]-x0[j])

        #checa se alcançamos a precisão desejada
        if np.max(y) < e:
            return print('\n',k,'ª iteração:\nx=',x,'\nerro=',np.max(y))

        print('\n',k,'ª iteração:\nx=',x,'\nerro=',np.max(y))
        #atualizamos o valor do chute começamos de novo
        x0 = x
    return

# Eliminação de Gauss com pivotamento parcial

In [9]:
#matriz coeficientes
A = np.array([[0, 5, -1], [11, 0, 1], [1, -1, -1]])
#matriz vetor resultante
b = np.array([5, 14, 0])

#matriz aumentada
Ab = np.hstack([A, b.reshape(-1, 1)])

#teste
Egauss(Ab)

Sendo a matriz aumentada:
 [[ 0  5 -1  5]
 [11  0  1 14]
 [ 1 -1 -1  0]]

Trocamos as linhas: 1 e 2 
 [[11.  0.  1. 14.]
 [ 0.  5. -1.  5.]
 [ 1. -1. -1.  0.]]

Eliminamos o elemento 3 1 :
 [[11.          0.          1.         14.        ]
 [ 0.          5.         -1.          5.        ]
 [ 0.         -1.         -1.09090909 -1.27272727]]

Eliminamos o elemento 3 2 :
 [[11.          0.          1.         14.        ]
 [ 0.          5.         -1.          5.        ]
 [ 0.          0.         -1.29090909 -0.27272727]]

A solução é x = [1.25352113 1.04225352 0.21126761]


# Método iterativo de Jacobi

In [10]:
#matriz coeficientes
A = np.array([[11, 0, 1], [0, 5, -1], [1, -1, -1]])
#matriz vetor resultante
b=np.array([14, 5, 0])

#vetor "chute"
x0=np.array([0,0,0])

#tolerância
e=10**(-3)

#nº máximo de iterações
N=10

Jacobi(A,b,x0,e,N)

0 ª iteração:
x= [0 0 0]

 1 ª iteração:
x= [1.27272727 1.         0.        ] 
erro= 1.2727272727272727

 2 ª iteração:
x= [1.27272727 1.         0.27272727] 
erro= 0.2727272727272727

 3 ª iteração:
x= [1.24793388 1.05454545 0.27272727] 
erro= 0.05454545454545445

 4 ª iteração:
x= [1.24793388 1.05454545 0.19338843] 
erro= 0.07933884297520644

 5 ª iteração:
x= [1.25514651 1.03867769 0.19338843] 
erro= 0.015867768595041243

 6 ª iteração:
x= [1.25514651 1.03867769 0.21646882] 
erro= 0.023080390683696272

 7 ª iteração:
x= [1.25304829 1.04329376 0.21646882] 
erro= 0.0046160781367392545

 8 ª iteração:
x= [1.25304829 1.04329376 0.20975452] 
erro= 0.006714295471620613

 9 ª iteração:
x= [1.25365868 1.0419509  0.20975452] 
erro= 0.0013428590943240781

 10 ª iteração:
x= [1.25365868 1.0419509  0.21170777] 
erro= 0.001953249591744033


# Método Iterativo de Gauss-Seidel

In [11]:
#matriz coeficientes
A = np.array([[11, 0, 1], [0, 5, -1], [1, -1, -1]])
#matriz vetor resultante
b=np.array([14, 5, 0])

#vetor "chute"
x0=np.array([0,0,0])

#tolerância
e=10**(-3)

#nº máximo de iterações
N=10

GSeidel(A,b,x0,e,N)

0 ª iteração:
x= [0 0 0]

 1 ª iteração:
x= [1.27272727 1.         0.27272727] 
erro= 1.2727272727272727

 2 ª iteração:
x= [1.24793388 1.05454545 0.19338843] 
erro= 0.07933884297520644

 3 ª iteração:
x= [1.25514651 1.03867769 0.21646882] 
erro= 0.023080390683696272

 4 ª iteração:
x= [1.25304829 1.04329376 0.20975452] 
erro= 0.006714295471620613

 5 ª iteração:
x= [1.25365868 1.0419509  0.21170777] 
erro= 0.001953249591744033

 6 ª iteração:
x= [1.25348111 1.04234155 0.21113956] 
erro= 0.0005682180630528499
